import {
  ADMIN_CAP_TYPE,
  ARENA_MATCH_TYPE,
  GAME_CONFIG_ID,
  MODULE,
  MONSTER_TYPE,
  PACKAGE_ID,
  TREASURY_ID,
} from "./constants";

export { ADMIN_CAP_TYPE, ARENA_MATCH_TYPE, GAME_CONFIG_ID, MODULE, MONSTER_TYPE, PACKAGE_ID, TREASURY_ID };

export const ACTIVE_PLAYER_EVENT_TYPES = [] as const;
